### ISSUE TITLE
在react native中listview不能上下滑动

### ISSUE THREAD

**Issue by Mrshutao** [react-component/swipeout#16]
好像不适用于listview，在你定义了左滑右滑的手势之后，listview的上下滑动就失效了，是否存在这个问题？

**Comment by paranoidjk** [comment]
please provide a reproducible demo

**Comment by lanten** [comment]
can slide on listview
but I would like to disable the slide menu when the listview is scrolling

**Comment by silentcloud** [comment]
@Mrshutao RN 见这里 https://github.com/silentcloud/react-native-swipeout，配合这个 listview 使用： https://github.com/dancormier/react-native-listitem

**Comment by predescu** [comment]
There is a way to use this component in react native with a ListView?
In my case, onPress action on the render row doesn't work.
