### ISSUE TITLE
Dependency not found when used with react native

### ISSUE THREAD

**Issue by jamiltz** [react-component/swipeout#22]
Steps to repro

1. Install

  ```javascript
  npm install --save rc-swipeout
  ```

2. Import in file

  ```javascript
  import Swipeout from 'rc-swipeout';
  ```

3. Run, error displayed:

<img src="https://cloud.githubusercontent.com/assets/2589337/21567379/a03ff480-cea3-11e6-8928-463651abcc4b.png" width="25%" />

**Comment by silentcloud** [comment]
main field is: `"main": "./lib/index.web"`
 so you need to 
```
import Swipeout from 'rc-swipeout/lib'
```

**Comment by jamiltz** [comment]
Thanks, submitted PR to update the instructions in the README.
