### ISSUE TITLE
左滑删除之后之后 删除显示问题

### ISSUE THREAD

**Issue by renxj** [react-component/swipeout#24]
![image](https://cloud.githubusercontent.com/assets/19201241/21672308/ae554724-d35c-11e6-8af9-5cdd1fb7f5e6.png)
多条记录删除上一条记录之后，记录删掉只有然后删除按钮出现在下一条记录，即原来的位置，删除最后一条记录则不会出现。

**Comment by silentcloud** [comment]
@renxj 你使用方式可能有问题，按下面这种来：
```js
[ ].map(item => <SwipeOut>{children}</SwipeOut>)
```

swipe  跟着 item 走

**Comment by renxj** [comment]
嗯 谢谢啦 加上autoClose这个参数就好了
