### ISSUE TITLE
onPress/onClick doesn't fire

### ISSUE THREAD

**Issue by niba** [react-component/swipeout#26]
I just downloaded the newest version of antd-mobile and SwipeAction components stopped firing onPress events. Reverting these changes from this pull request fixed everything: https://github.com/react-component/swipeout/commit/4f08ee160d9321e042ef528f88c1a64e8b3c90bf

Ok, the problem is that firing preventDefault in `touchstart` suppresses onClick event. You need to change `touchstart` to `touchmove`

Source: http://stackoverflow.com/questions/6780965/why-onclick-event-suppressed-when-preventdefault-is-called-for-the-touchstart

Chrome: 55.0.2883.87 m

**Comment by silentcloud** [comment]
- `click event`:  can't be used; when there are mutiple  `Swipeout` (eg:  https://react-component.github.io/swipeout/examples/mutiple.html),  tap one, the other one can not be hiddened;
- `touchmove`: tap one, then it can not be hidden unless you move;

my English is poor, i hope you can understand; 

I have tested in chrome ( 55.0.2883.95 (64-bit)) & my iPhone (ios 10.2), `onPress`  can be fired;  


![test](https://cloud.githubusercontent.com/assets/1698185/22012770/c2111ffe-dcd0-11e6-8e7c-5dd78d7e4053.gif)

**Comment by paranoidjk** [comment]
@niba 
please make sure you use Chrome simulator or a mobile browser, otherwise `TouchEvent` is not supported on PC browser.
going to close this, if you have further question, feel free to repoen.
