### ISSUE TITLE
Can't figure out how to close?

### ISSUE THREAD

**Issue by rubencodes** [react-component/swipeout#28]
Component slides open just fine, but then I can't get it to close without clicking a button. Clicking the button closes if I have autoClose flag set, but how can I swipe back to close?

BTW Absolutely *love* this component, it's so simple & the animation is so smooth! Great work!

**Comment by silentcloud** [comment]
`close` by swipe left / right or click document.body (only web)

check this example: 
https://react-component.github.io/swipeout/examples/mutiple.html


![test](https://cloud.githubusercontent.com/assets/1698185/22198631/5269fb64-e192-11e6-98fb-74f30f5a2bb2.gif)

**Comment by rubencodes** [comment]
Hmmm, interesting; I think I may be encountering a bug then. I'm at work at the moment but will update with a GIF of behavior & further details shortly.

**Comment by rubencodes** [comment]
So this is the code I'm using:

```
const actions = {
      Delete: {
        text: 'Delete',
        onPress:() => this.handleDelete(),
        style: { backgroundColor: 'red', color: 'white' }
      }
}

return (
      <Swipeout  right={[ actions.Delete ]} autoClose>
          <li className={ `list-group-item` } onClick={ () => this.props.onClick(_id) }>
              <b className="list-group-item-heading">{ name }</b>
              <p className="list-group-item-text">{ details }</p>
          </li>
      </Swipeout>
);
```

And this is the behavior I'm seeing:
![image](https://media.giphy.com/media/26xBseQCU28OfsKac/giphy.gif)

As you can see, the initial swipe left works well, but I can't swipe back, and clicking elsewhere doesn't make it go away :/ Any ideas? Or extra helpful information I could provide? Thanks!

**Comment by rubencodes** [comment]
**UPDATE**: I've noticed it will drag back fine as long as I haven't let go of the mouse; e.g. if I click and drag it in one direction, then drag it back, it will work, but if I let go anywhere in between, it doesn't let me drag back.

**Comment by rubencodes** [comment]
**Update #2**: After further debugging, it seems the reason it's not working is you're listening to the `touchstart` event, which does not fire on desktop web unless you're in the emulator. Changing the event to 'mousedown' on web produces better results.

**Comment by silentcloud** [comment]
@rubencodes yes, only mobile now

**Comment by paranoidjk** [comment]
associated with https://github.com/ant-design/ant-design-mobile/issues/943
I think pc support is not necessary，since one should not use `swipeout` on pc, it's strange.
