### ISSUE TITLE
Does not work with TextInput

### ISSUE THREAD

**Issue by mehulmpt** [react-component/swipeout#34]
I'm using it to wrap a TextInput and the TextInputs are not clickable/usable anymore. Can you see into the issue?

> Swipeout right={
> 	[{
> 	    text: 'ok'
> 		}]
> 	}>
> 	<View key={e.id} style={styles.person}>					
> 	<TextInput /
>  

The TextInput is no longer useable

**Comment by silentcloud** [comment]
@mehulmpt  Try to use new version.  Also the `TextInput` should not be full column.
