### ISSUE TITLE
Update Hammer library to one that's being maintained

### ISSUE THREAD

**Issue by ljknight** [react-component/swipeout#35]
Warning in console: Hammer: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.

The current react-hammer library appears to not be maintained anymore - this fork is being updated and no longer shows the warning: https://github.com/react-component/react-hammerjs

**Comment by silentcloud** [comment]
@ljknight Ok, thanks

**Comment by silentcloud** [comment]
version 1.3.2
