### ISSUE TITLE
[Resolved] Chrome warning 'Unable to preventDefault inside passive event listener'

### ISSUE THREAD

**Issue by cncolder** [react-component/swipeout#38]
Chrome56 touchstart 事件默认是被动事件（passive）, 不能调用 preventDefault。详见 [Scrolling Intervention](https://developers.google.com/web/updates/2017/01/scrolling-intervention)

大体上有两条路可选：

1. `document.body.addEventListener('touchstart', this.onCloseSwipe.bind(this), {passive: false});` 但并不是所有浏览器都支持 [EventListenerOptions](https://github.com/WICG/EventListenerOptions)。
2. 官方建议是用 touch-action CSS 属性来控制元素对 touch 事件的响应。

我查了半天竟然没有找到一个变量来指示 preventDefault 是否可以调用。Modernizr 给出的测试代码是 try catch。

```
Unable to preventDefault inside passive event listener due to target being treated as passive.
See https://www.chromestatus.com/features/5093566007214080
onCloseSwipe @ Swipeout.web.js?5589b3f:97
```

**Comment by silentcloud** [comment]
@cncolder  

![image](https://cloud.githubusercontent.com/assets/1698185/26292070/b3bf6f9c-3ee5-11e7-879a-6298ef8dc2be.png)

add `touch-action: none`

**Comment by cncolder** [comment]
ok resolved
