### ISSUE TITLE
the buttons total width  unequal the parent's width 

### ISSUE THREAD

**Issue by keith890303** [react-component/swipeout#40]
I have two right buttons : one width is '50px' another '70px' ; i think the parent container(`<div class="rc-swipeout-actions rc-swipeout-actions-right"></div>`) should be '120px' . unfortunately  is still '150px'.
finally i find the reason that my screen width is '375px' ,the parent container has a limit width: 375/5 * 2 
 (buttons count)  = 150, so the width not depend on the children's total width  but the  screen‘s width and buttons count  .......

**Comment by keith890303** [comment]
in my local env i try change like blow , it's run ok. is there any question every body ?
```
//auto get children's total width method
function getBtnWidth(btns, width){
    var btnsWidth = 0;
    if(btns.length > 0) {
        btns.map(function (btn, i) {
            if (btn.style != undefined && btn.style.width != undefined && btn.style.width.indexOf("px")> 0) {
                btnsWidth += parseFloat(btn.style.width.replace("px",""));
            } else {
                btnsWidth += width / 5
            }
        })
    } else {
        btnsWidth = width / 5 * btns.length;
    }
    return btnsWidth;
}
//react didmount  set left and right buttons width
this.btnsLeftWidth = getBtnWidth(left,width);
this.btnsRightWidth = getBtnWidth(right,width);
//instead of the origin code
this.btnsLeftWidth = width / 5 * left.length;
this.btnsRightWidth = width / 5 * right.length;
```

**Comment by silentcloud** [comment]
@keith890303 can you send a PR

**Comment by silentcloud** [comment]
这个我重新来实现了，按照 iOS 的样式表现来做（button 始终是显示的，被 content 覆盖）
