### ISSUE TITLE
点击svg标签时报错

### ISSUE THREAD

**Issue by unordered** [react-component/swipeout#45]
https://github.com/react-component/swipeout/blob/b4ad726f7e8accf49077140526fbb9b41b03a512/src/Swipeout.tsx#L54
```
Uncaught TypeError: node.className.indexOf is not a function
```

当打开一条以上的情况下，并且开启了autoClose，当列表中有svg标签时，点击svg标签会导致错误

**Comment by silentcloud** [comment]
给出代码示例，github 地址或者打包代码上来

**Comment by paranoidjk** [comment]
@silentcloud svg 不能用 className https://developer.mozilla.org/en-US/docs/Web/API/Element/className#Notes

另外这里可以用阻止冒泡的方案，没必要读取 dom， 我改一下

**Comment by paranoidjk** [comment]
还不能用阻止冒泡的方案，SwipeAction 在一个页面可能有多实例，设计的交互是开一个必须要关闭其他。
