### ISSUE TITLE
Please upgrade react-native-swipeout to the latest version which fixes the ViewPropTypes error 

### ISSUE THREAD

**Issue by bang88** [react-component/swipeout#47]

**Comment by silentcloud** [comment]
@bang88 ok

**Comment by hassanAwanAlvi** [comment]
I am at 2.0.11 and still getting this warning.

<img width="1308" alt="Screenshot 2022-07-04 at 1 55 16 pm" src="https://user-images.githubusercontent.com/17249527/177159279-449286d5-54a3-4d76-a5e4-e5b7f0bb0515.png">
g...
