### ISSUE TITLE
how to prevent event bind to this component's children when I just want to close the swipe?

### ISSUE THREAD

**Issue by susan-github** [react-component/swipeout#9]
When the swipe is opened (such as the right buttons is visible), then I tap the list item intend to close it. But now, the event which is bound on the child be fired.
**Before:** 
`<Swipeout
                      right={[
                          {
                              text: '删除',
                              onPress: () => this.handleDelete(),
                              style: { backgroundColor: '#fc352b', color: 'white' },
                          },
                      ]}
                      onClose={() => { console.log('close!'); }}
                    ><div onClick={()=>{browserHistory.push('/pageTwo');}}>Go to page two</div>
</Swipeout>`

While I has an idea is  that bind another event to the component, only when the swipe is closed can be fired.

**Modified:** 
(1)file:Swipeout.out.js 
`Swipeout.prototype.onTap = function onTap() {
    if (this.openedLeft || this.openedRight) {
      this.close();
    }else{
      this.props.onPress();
    }
  };`
(2)
`<Swipeout
                      right={[
                          {
                              text: '删除',
                              onPress: () => this.handleDelete(),
                              style: { backgroundColor: '#fc352b', color: 'white' },
                          },
                      ]}
                      onClose={() => { console.log('close!'); }}
                      onPress={()=>{browserHistory.push('/pageTwo');}}
                    ><div>Go to page two</div>
</Swipeout>`

Would you give some suggestions?

**Comment by silentcloud** [comment]
@susan-github 

```javascript
onTap(e) {
  if (this.openedLeft || this.openedRight) {
    e.preventDefault(); // this will resolve your problem
    this.close();
  }
}
```
I will fix it later, and publish a hotfix

**Comment by susan-github** [comment]
yeah, this solution is more professional, Thanks! 😄 @silentcloud

**Comment by silentcloud** [comment]
@susan-github  version 1.1.5

**Comment by susan-github** [comment]
Got it! 😆
